### PR TITLE
added rulers for the annotation scene, and fixed a minor bug (img == …

### PR DESCRIPTION
**Pull request by prinsherbert**
…None -> img is None)

### CODE REVIEW

**Comment by prinsherbert** [comment]
@nilsonholger Could you state why this should not be merged?

**Comment by nilsonholger** [comment]
@prinsherbert Well, similar functionality was added just recently (rulers for the annotation scene). Furthermore, somehow the build was broken (at least as report by travis-ci).

But now that I look at your commit in detail, it seems you have added rulers in general while the added functionality was for `rect` items only, IIRC. Might be interesting to add your version instead. Could you please file a new pull request, ensure that the build is passing and definitely separate the included bugfix (`img == ...`) into its own pull request? Sorry for the additional work, but I would rather not reopen this pull request as is right now.

**Comment by prinsherbert** [comment]
Hi @nilsonholger I have loads of PR's that are in a similar state, so be patient then :)

**Comment by nilsonholger** [comment]
@prinsherbert Well, it took almost 6 months for your pull request to be looked at (sorry for that), so time is not an issue at all! I'll be patient, no questions asked! Looking forward to them!

**Comment by prinsherbert** [comment]
@nilsonholger Well, that is part of the problem. I can remember a scavenger hunt through the code to decide where to implement it, and how to do so. So I might have some duplicate research going on to make the tests pass.

**Comment by prinsherbert** [comment]
Could you point to the documentation regarding running tests (could not find them) or paste the commands there? Thanks!

**Comment by nilsonholger** [comment]
@prinsherbert Sorry for the duplicate effort! I'm afraid the tests have to be run manually, sadly there is no such thing as `python setup.py test`. Don't worry about the tests for now!

**Pull request closed without merging**
